# [target.x86_64-unknown-linux-musl]
# pre-build = [
#     "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git gperf gettext autopoint make python3 libfreetype-dev libexpat1-dev libclang-dev && cd / && git clone http://gitlab.freedesktop.org/fontconfig/fontconfig.git && cd /fontconfig && ./autogen.sh --sysconfdir=/etc --prefix=/usr --mandir=/usr/share/man && make install"
# ]

[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y libfontconfig1-dev libclang-8-dev"]

[target.i686-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y libfontconfig1-dev libclang-8-dev"]